# 线上环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.163.186:3306/weblog?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root14357
  cache:
    type: redis
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    host: 172.30.163.186
    port: 6379
    password:

dubbo:
  application:
    name: weblog-shopping-service
  registry:
    address: zookeeper://172.30.163.186:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

logging:
  level:
    com.jale.weblog.shopping: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.jale.weblog.shopping.api.dataobject